import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { PlanOutput } from "../subagents.js";
import type { PlanCheckOutput, VerificationOutput } from "../orchestration.js";

export function writePlanFiles(phaseDir: string, planOutput: PlanOutput): string[] {
  return planOutput.plans.map((plan) => {
    const path = join(phaseDir, `${plan.phase}-${plan.plan}-PLAN.md`);
    const taskLines =
      plan.tasks === undefined || plan.tasks.length === 0
        ? ["- No structured tasks provided by planner."]
        : plan.tasks.flatMap((task, index) => [
            `### Task ${index + 1}: ${task.title}`,
            "",
            `Files: ${task.files.join(", ")}`,
            "",
            "Action:",
            task.action,
            "",
            "Verify:",
            task.verify,
            "",
            "Done:",
            task.done,
            "",
          ]);
    writeFileSync(
      path,
      [
        "---",
        `phase: ${plan.phase}`,
        `plan: ${plan.plan}`,
        `type: ${plan.type}`,
        `wave: ${plan.wave}`,
        `depends_on: [${plan.depends_on.join(", ")}]`,
        `files_modified: [${plan.files_modified.join(", ")}]`,
        `autonomous: ${String(plan.autonomous)}`,
        `must_haves: [${plan.must_haves.join(", ")}]`,
        "---",
        "",
        `# Plan ${plan.phase}-${plan.plan}`,
        "",
        "## Objective",
        "",
        plan.objective ?? "Generated by GSD planner.",
        "",
        "## Must Haves",
        "",
        ...plan.must_haves.map((item) => `- ${item}`),
        "",
        ...(plan.notes === undefined || plan.notes.length === 0
          ? []
          : ["## Notes", "", ...plan.notes.map((item) => `- ${item}`), ""]),
        "## Tasks",
        "",
        ...taskLines,
        "",
      ].join("\n"),
      "utf8",
    );
    return path;
  });
}

export function writePlanCheckReport(
  phaseDir: string,
  phaseNumber: string,
  check: PlanCheckOutput,
): string {
  const path = join(phaseDir, `${phaseNumber}-PLAN-CHECK.md`);
  writeFileSync(
    path,
    [
      "---",
      `phase: ${phaseNumber}`,
      `approved: ${String(check.approved)}`,
      "---",
      "",
      `# Plan Check ${phaseNumber}`,
      "",
      "## Summary",
      "",
      check.summary,
      "",
      ...(check.coverage === undefined || check.coverage.length === 0
        ? []
        : [
            "## Coverage",
            "",
            ...check.coverage.map(
              (entry) =>
                `- ${entry.requirement}: ${entry.status}${entry.notes !== undefined && entry.notes.length > 0 ? ` (${entry.notes})` : ""}`,
            ),
            "",
          ]),
      "## Issues",
      "",
      ...(check.issues.length === 0
        ? ["None"]
        : check.issues.map(
            (issue) =>
              `- ${issue.severity.toUpperCase()}: ${issue.description}${issue.fix_hint !== undefined && issue.fix_hint.length > 0 ? ` (${issue.fix_hint})` : ""}`,
          )),
      "",
    ].join("\n"),
    "utf8",
  );
  return path;
}

export function writeVerificationReport(
  phaseDir: string,
  phaseNumber: string,
  verification: VerificationOutput,
): string {
  const path = join(phaseDir, `${phaseNumber}-VERIFICATION.md`);
  writeFileSync(
    path,
    [
      "---",
      `phase: ${phaseNumber}`,
      `verified: ${String(verification.verified)}`,
      "---",
      "",
      `# Verification ${phaseNumber}`,
      "",
      "## Summary",
      "",
      verification.summary,
      "",
      ...(verification.truths === undefined || verification.truths.length === 0
        ? []
        : [
            "## Truths",
            "",
            ...verification.truths.map(
              (truth) =>
                `- ${truth.truth}: ${truth.status}${truth.evidence !== undefined && truth.evidence.length > 0 ? ` (${truth.evidence})` : ""}`,
            ),
            "",
          ]),
      "## Blockers",
      "",
      ...(verification.blockers.length === 0
        ? ["None"]
        : verification.blockers.map((item) => `- ${item}`)),
      "",
      "## Warnings",
      "",
      ...(verification.warnings.length === 0
        ? ["None"]
        : verification.warnings.map((item) => `- ${item}`)),
      "",
      ...(verification.uat_items === undefined || verification.uat_items.length === 0
        ? []
        : [
            "## UAT",
            "",
            ...verification.uat_items.map(
              (item) =>
                `- ${item.name}: ${item.result}${item.reason !== undefined && item.reason.length > 0 ? ` (${item.reason})` : ""}`,
            ),
            "",
          ]),
    ].join("\n"),
    "utf8",
  );
  return path;
}

export function writeValidationArtifact(
  phaseDir: string,
  phaseNumber: string,
  verification: VerificationOutput,
): string {
  const path = join(phaseDir, `${phaseNumber}-VALIDATION.md`);
  writeFileSync(
    path,
    [
      `# Validation ${phaseNumber}`,
      "",
      "## Status",
      "",
      verification.verified ? "Validated" : "Needs follow-up",
      "",
      "## Summary",
      "",
      verification.summary,
      "",
      "## Automated Findings",
      "",
      ...(verification.blockers.length === 0
        ? ["- No blockers"]
        : verification.blockers.map((item) => `- Blocker: ${item}`)),
      ...(verification.warnings.length === 0
        ? ["- No warnings"]
        : verification.warnings.map((item) => `- Warning: ${item}`)),
      "",
    ].join("\n"),
    "utf8",
  );
  return path;
}

export function writeUatArtifact(
  phaseDir: string,
  phaseNumber: string,
  verification: VerificationOutput,
): string | undefined {
  if (verification.uat_items === undefined || verification.uat_items.length === 0) {
    return undefined;
  }
  const path = join(phaseDir, `${phaseNumber}-UAT.md`);
  writeFileSync(
    path,
    [
      `# UAT ${phaseNumber}`,
      "",
      ...verification.uat_items.map(
        (item) =>
          `- ${item.name}\n  - result: ${item.result}${item.reason !== undefined && item.reason.length > 0 ? `\n  - reason: ${item.reason}` : ""}`,
      ),
      "",
    ].join("\n"),
    "utf8",
  );
  return path;
}
