import type { ExtensionAPI, ExtensionCommandContext } from "@mariozechner/pi-coding-agent";
import { Type, type Static } from "typebox";

import { buildLaunchCommand } from "../subagent-sdk/launch.js";
import { createSubagentSDK, type SubagentHandle, type SubagentSDK } from "../subagent-sdk/sdk.js";
import { TmuxAdapter } from "../subagent-sdk/tmux.js";
import type { MuxAdapter } from "../subagent-sdk/mux.js";
import { errorMessage } from "../utils/error-message.js";
import { Value } from "typebox/value";

const COMMIT_SUMMARY_MESSAGE_TYPE = "commit-summary";

const GitCommitShaSchema = Type.String({
  minLength: 7,
  maxLength: 40,
  pattern: "^[0-9a-f]{7,40}$",
  description: "Required. Lowercase git commit SHA (short or full).",
});

const CommitMessageSchema = Type.String({
  minLength: 1,
  maxLength: 200,
  description: "Required. Conventional Commit subject line for the commit.",
});

const CommitFilePathSchema = Type.String({
  minLength: 1,
  maxLength: 4096,
  description: "Required. Repository-relative file path included in this commit.",
});

const CommitWarningSchema = Type.String({
  minLength: 1,
  maxLength: 2000,
  description: "Required item. Warning or non-fatal issue encountered while committing.",
});

const RemainingChangeSchema = Type.String({
  minLength: 1,
  maxLength: 4096,
  description: "Required item. Remaining modified/untracked file after commit workflow.",
});

const CommitStructuredSummarySchema = Type.Object(
  {
    summaryMarkdown: Type.String({
      minLength: 1,
      maxLength: 20_000,
      description:
        "Required. Markdown commit summary, typically git-log style bullet lines for created commits.",
    }),
    commits: Type.Array(
      Type.Object(
        {
          sha: GitCommitShaSchema,
          message: CommitMessageSchema,
          files: Type.Array(CommitFilePathSchema, {
            minItems: 0,
            maxItems: 10_000,
            description:
              "Required. Files included in this commit. Empty array is allowed when unavailable.",
          }),
        },
        {
          additionalProperties: false,
          description: "Required item. One commit generated by the commiter workflow.",
        },
      ),
      {
        minItems: 0,
        maxItems: 1_000,
        description: "Required. Ordered list of commits created in this run.",
      },
    ),
    warnings: Type.Array(CommitWarningSchema, {
      minItems: 0,
      maxItems: 1_000,
      description: "Required. Non-blocking warnings. Empty array means no warnings.",
    }),
    remainingChanges: Type.Array(RemainingChangeSchema, {
      minItems: 0,
      maxItems: 10_000,
      description:
        "Required. Remaining working-tree changes after commit workflow. Empty array means clean tree.",
    }),
  },
  {
    additionalProperties: false,
    description:
      "Structured result for /commit. All top-level fields are required unless explicitly marked optional.",
  },
);

type CommitStructuredSummary = Static<typeof CommitStructuredSummarySchema>;

type CreateCommitExtensionOptions = {
  adapterFactory?: (pi: ExtensionAPI) => MuxAdapter;
  sdkFactory?: (input: {
    pi: ExtensionAPI;
    adapter: MuxAdapter;
  }) => Pick<SubagentSDK, "start" | "dispose">;
  enabled?: boolean;
};

function isCommitStructuredSummary(value: unknown): value is CommitStructuredSummary {
  return Value.Check(CommitStructuredSummarySchema, value);
}

function buildCommitTask(extraDetails?: string): string {
  const trimmedExtraDetails = extraDetails?.trim();
  return [
    "Use the commiter mode workflow to analyze local changes and create atomic conventional commits.",
    "Execute the needed git add + git commit commands and stop immediately if git reports signing, hook, or policy failures.",
    trimmedExtraDetails !== undefined && trimmedExtraDetails.length > 0
      ? `Additional user details:\n${trimmedExtraDetails}`
      : undefined,
  ]
    .filter((value): value is string => value !== undefined && value.length > 0)
    .join("\n\n");
}

function formatCommitSummary(summary: CommitStructuredSummary): string {
  const sections = [summary.summaryMarkdown.trim() || "No commits created."];

  if (summary.commits.length > 0) {
    sections.push(
      [
        "## Commit Details",
        ...summary.commits.map((commit) => {
          const files = commit.files.length > 0 ? commit.files.join(", ") : "(none)";
          return `- ${commit.sha} ${commit.message}\n  files: ${files}`;
        }),
      ].join("\n"),
    );
  }

  if (summary.warnings.length > 0) {
    sections.push(["## Warnings", ...summary.warnings.map((warning) => `- ${warning}`)].join("\n"));
  }

  if (summary.remainingChanges.length > 0) {
    sections.push(
      ["## Remaining Changes", ...summary.remainingChanges.map((item) => `- ${item}`)].join("\n"),
    );
  }

  return sections.join("\n\n");
}

async function ensureGitRepository(
  pi: ExtensionAPI,
  ctx: ExtensionCommandContext,
): Promise<boolean> {
  const gitCheck = await pi.exec("git", ["rev-parse", "--git-dir"]);
  if (gitCheck.code === 0) {
    return true;
  }

  ctx.ui.notify("Not a git repository", "error");
  return false;
}

export function createCommitExtension(options?: CreateCommitExtensionOptions) {
  const resolvedOptions = options ?? { enabled: true };
  return (pi: ExtensionAPI): void => {
    if (resolvedOptions.enabled === false) {
      return;
    }

    const sdk = createCommitSdk(pi, resolvedOptions);
    const state = { running: false };
    pi.registerCommand("commit", {
      description: "Create atomic commits using the commiter subagent mode",
      handler: createCommitCommandHandler(pi, sdk, state),
    });
    pi.on("session_shutdown", () => {
      sdk.dispose();
    });
  };
}

function createCommitSdk(
  pi: ExtensionAPI,
  options: CreateCommitExtensionOptions,
): Pick<SubagentSDK, "start" | "dispose"> {
  const adapter =
    options.adapterFactory?.(pi) ??
    new TmuxAdapter(
      (command, args, execOptions) => pi.exec(command, args, execOptions),
      process.cwd(),
    );
  return (
    options.sdkFactory?.({ pi, adapter }) ??
    createSubagentSDK(pi, {
      adapter,
      buildLaunchCommand,
    })
  );
}

async function waitForCommitCompletion(
  pi: ExtensionAPI,
  ctx: ExtensionCommandContext,
  handle: SubagentHandle,
): Promise<void> {
  const terminal = await handle.waitForCompletion();
  if (terminal.status !== "completed") {
    ctx.ui.notify(`Commit failed: ${terminal.summary ?? "No summary available."}`, "error");
    return;
  }

  if (!isCommitStructuredSummary(terminal.structured)) {
    ctx.ui.notify("Commit failed: Structured output missing or invalid.", "error");
    return;
  }

  pi.sendMessage(
    {
      customType: COMMIT_SUMMARY_MESSAGE_TYPE,
      content: formatCommitSummary(terminal.structured),
      display: true,
    },
    { deliverAs: "steer", triggerTurn: false },
  );
}

function monitorDetachedCommit(
  pi: ExtensionAPI,
  ctx: ExtensionCommandContext,
  state: { running: boolean },
  handle: SubagentHandle,
): void {
  waitForCommitCompletion(pi, ctx, handle)
    .catch((error: unknown) => {
      ctx.ui.notify(`Commit failed: ${errorMessage(error)}`, "error");
    })
    .finally(() => {
      state.running = false;
    });
}

function createCommitCommandHandler(
  pi: ExtensionAPI,
  sdk: Pick<SubagentSDK, "start" | "dispose">,
  state: { running: boolean },
) {
  return async (args: string, ctx: ExtensionCommandContext): Promise<void> => {
    if (state.running) {
      ctx.ui.notify("A commit job is already running.", "warning");
      return;
    }
    if (!(await ensureGitRepository(pi, ctx))) {
      return;
    }

    state.running = true;
    ctx.ui.notify("Starting commiter subagent...", "info");

    try {
      const started = await sdk.start(
        {
          name: "commit",
          task: buildCommitTask(args.trim() || undefined),
          mode: "commiter",
          cwd: ctx.cwd,
          persisted: false,
          completion: false,
          outputFormat: { type: "json_schema", schema: CommitStructuredSummarySchema },
        },
        ctx,
      );

      monitorDetachedCommit(pi, ctx, state, started.handle);
    } catch (error) {
      state.running = false;
      ctx.ui.notify(`Commit failed: ${errorMessage(error)}`, "error");
    }
  };
}

export default createCommitExtension();
